import createClient from "openapi-fetch";
import type { paths } from "./schema.gen"; // generated by openapi-typescript
import { NextRequest } from "next/server";
import { User } from "firebase/auth";

type FetchClientOptions = {
  user: User;
};

export const getFetchClient = async ({ user }: FetchClientOptions) => {
  const baseUrl = process.env.NEXT_PUBLIC_API_BASE_URL;
  let headers: Record<string, string> = {};

  if (user) {
    const token = await user.getIdToken();
    if (token) {
      headers.Authorization = `Bearer ${token}`;
    }
  }

  return createClient<paths>({
    baseUrl,
    headers,
  });
};

export default getFetchClient;
