{
  "openapi" : "3.0.1",
  "info" : {
    "contact" : { },
    "title" : "AuthTempGo API"
  },
  "servers" : [ {
    "url" : "//localhost:8080/"
  } ],
  "paths" : {
    "/test" : {
      "get" : {
        "description" : "Verify the health of the server",
        "responses" : {
          "200" : {
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            },
            "description" : "ok"
          },
          "401" : {
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            },
            "description" : "Unauthorized"
          }
        },
        "security" : [ {
          "Bearer" : [ ]
        } ],
        "tags" : [ "verify" ]
      }
    }
  },
  "components" : {
    "schemas" : { }
  },
  "x-original-swagger-version" : "2.0"
}